### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jeff-h** [hyjk2000/devdocs-mac#1]
Thanks for creating this!

Also, I think this is the perfect use-case for MacGap :) So lightweight, such a tiny app size.

My only request would be a new app icon. The current one is virtually invisible in my doc.

**Comment by hyjk2000** [comment]
Thanks for trying out. I'm very happy with MacGap, it's much superior for packaging web apps for Mac, especially for developers with experience of Xcode. Fine-tuning UI and menu is much easier.

As for the icon, I'm eating my own dog food so I noticed too. I think I'll draw a new one when I got time.

**Comment by hyjk2000** [comment]
New app icon added in [v0.0.4](https://github.com/hyjk2000/devdocs-mac/releases/tag/v0.0.4).

**Comment by jeff-h** [comment]
Nice :)
